version: '2'
services:
  app:
    extends:
      file: docker-services.yml
      service: app
    volumes:
      - nycdb:/wow/nycdb/
    links:
      - db
  db:
    extends:
      file: docker-services.yml
      service: db
    ports:
      - 5432:5432
volumes:
  node-modules:
  client-node-modules:
  nycdb:
