version: '2'
services:
  app:
    extends:
      file: docker-services.yml
      service: app
    volumes:
      - .:/wow:delegated
    links:
      - db
  db:
    extends:
      file: docker-services.yml
      service: db
volumes:
  node-modules:
  client-node-modules:
